{% set name = "periodictable" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/python-periodictable/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 5a8aed4759e74dabb38fda0ecbe59b6f7fef42b0babf83f25d8dfaee3c6798f8

build:
  number: 0
  skip: true # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - numpy
    - pyparsing

test:
  source_files:
    - test
  imports:
    - periodictable
    - periodictable.activation
    - periodictable.constants
    - periodictable.core
    - periodictable.crystal_structure
    - periodictable.formulas
    - periodictable.nsf
    - periodictable.xsf
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v test

about:
  home: https://github.com/python-periodictable/periodictable
  license: Unlicense
  license_family: PUBLIC-DOMAIN
  license_file: License.txt
  summary: This package provides a periodic table of the elements with support for mass, density and xray/neutron scattering information.
  description: |
    The periodictable package provides an extensible periodic table
    of the elements prepopulated with data important to neutron and
    X-ray scattering experiments. With the elements pacakge you can
    compute the scattering potential of a compound at a given wavelength.
  doc_url: https://periodictable.readthedocs.io
  dev_url: https://github.com/python-periodictable/periodictable

extra:
  recipe-maintainers:
    - bjodah
    - mrakitin
